# Generated by Django 2.0.5 on 2019-05-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_tweetmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobilenumber', models.CharField(max_length=100)),
                ('feedback', models.CharField(max_length=300)),
            ],
        ),
    ]
